[package]
name = "cantucci"
version = "0.1.0"
authors = [
    "Lukas Kalbertodt <lukas.kalbertodt@gmail.com>",
    "Julian Kniephoff <me@juliankniephoff.com>",
]

[workspace]

[dependencies]
core = { path = "core/" }
arrayvec = "0.3"
cgmath = "0.11.0"
env_logger = "0.3"
error-chain = "0.4"
glium = "0.15"
log = "0.3"
num_cpus = "1"
term-painter = "0.2"
threadpool = "1"
