[package]
name = "cantucci"
version = "0.1.0"
authors = [
    "Lukas Kalbertodt <lukas.kalbertodt@gmail.com>",
    "Julian Kniephoff <me@juliankniephoff.com>",
]

[dependencies]
core = { path = "core/" }
glium = "0.15"
cgmath = "0.11.0"
error-chain = "0.4"
log = "0.3"
env_logger = "0.3"
term-painter = "0.2"
